# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35786a6e9c763887edf84a845c1b0ffc1a418e4ce31cca00c666ce0f854c81228ab13d5c654384bd8c5c9a01d65d00d732a0676b5067a112ba2fb6b20acba0d4

test:
  secret_key_base: f7c3a0dfbb7142e1c901dcce14c9affb665149efe1190c9bfbf30a0e52ad3109bf02263c625b13e5bce2ffded72581c4eddff8ecce17b9da5e1bf1374f10f748

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
